#!/usr/bin/env python3
"""Regenerate docs/features.tsv and docs/30-features/INDEX.md.

Source of truth is the feature files themselves: docs/30-features/<DOM>/F-*.md.
Both outputs are generated — never hand-edit them.
"""
import glob
import os
import re
import sys

SRC = "docs/30-features"
TSV = "docs/features.tsv"
INDEX = f"{SRC}/INDEX.md"

DOMAIN_NAMES = {
    "CAT": "Exercise catalogue",
    "ROU": "Routines & programs",
    "LOG": "Workout logging",
    "TIM": "Timers",
    "ANA": "Analytics & charts",
    "PRG": "Progression engine",
    "BOD": "Body metrics",
    "DAT": "Data portability",
    "SET": "Settings",
    "PLT": "Plate mathematics",
    "NAV": "App shell & navigation",
    "THM": "Theming",
    "A11Y": "Accessibility",
    "I18N": "Localisation",
    "HLT": "Health platform integration",
    "REL": "Release & distribution",
}
DOMAIN_ORDER = list(DOMAIN_NAMES)


def parse(path):
    text = open(path).read()
    m = re.match(r"# (F-[A-Z0-9]+-\d{3}) — (.+)", text)
    if not m:
        sys.exit(f"{path}: missing or malformed title heading")
    fid, title = m.group(1), m.group(2).strip()

    def field(name, default=""):
        """Read a header field. Fields share lines, separated by ' | '."""
        mm = re.search(rf"(?:^|\| ){name}:\s*([^|\n]*)", text, re.M)
        return mm.group(1).strip() if mm else default

    return {
        "id": fid,
        "domain": fid.split("-")[1],
        "title": title,
        "status": field("Status", "?"),
        "priority": field("Priority", "?"),
        "phase": field("Phase", "—"),
        "depends": field("Depends on"),
        "blocks": field("Blocks"),
        "reads": field("Reads"),
        "path": path,
    }


def sort_key(f):
    return (DOMAIN_ORDER.index(f["domain"]) if f["domain"] in DOMAIN_ORDER else 99,
            f["id"])


def main():
    files = sorted(glob.glob(f"{SRC}/*/F-*.md"))
    feats = sorted((parse(p) for p in files), key=sort_key)

    with open(TSV, "w") as fh:
        fh.write("id\tphase\tstatus\tpriority\ttitle\tdepends\tblocks\treads\n")
        for f in feats:
            fh.write("\t".join([
                f["id"], f["phase"], f["status"], f["priority"], f["title"],
                f["depends"], f["blocks"], f["reads"],
            ]) + "\n")

    phases = {}
    for f in feats:
        phases.setdefault(f["phase"], []).append(f)

    with open(INDEX, "w") as fh:
        fh.write("# Feature index\n\n")
        fh.write("**Generated by `tools/gen-index.sh` — do not edit.**\n\n")
        fh.write(f"{len(feats)} features. ")
        fh.write("For machine-readable project state see "
                 "[`../features.tsv`](../features.tsv); it answers most "
                 "questions without opening a spec.\n\n")
        fh.write("| Phase | Count |\n|---|---|\n")
        for p in sorted(phases, key=lambda x: (x == "—", x)):
            label = "backlog" if p == "—" else f"Phase {p}"
            fh.write(f"| {label} | {len(phases[p])} |\n")
        fh.write("\n")
        for dom in DOMAIN_ORDER:
            rows = [f for f in feats if f["domain"] == dom]
            if not rows:
                continue
            fh.write(f"## `{dom}` — {DOMAIN_NAMES[dom]}\n\n")
            fh.write("| ID | Title | Phase | Pri | Status |\n|---|---|---|---|---|\n")
            for f in rows:
                # Markdown links always use forward slashes, whatever the
                # host OS separator is.
                rel = os.path.relpath(f["path"], SRC).replace(os.sep, "/")
                fh.write(f"| [{f['id']}]({rel}) | {f['title']} | "
                         f"{f['phase']} | {f['priority']} | {f['status']} |\n")
            fh.write("\n")

    print(f"wrote {TSV} and {INDEX} ({len(feats)} features)")


if __name__ == "__main__":
    main()
